spring.application.name=stocklurker

# Configuración de la base de datos H2
spring.datasource.url=jdbc:h2:file:./data/stocklurker_db;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.sql.init.mode=never
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuración de Liquibase
spring.liquibase.enabled=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.defer-datasource-initialization=false
logging.level.liquibase=info
logging.level.liquibase.util=warn
spring.liquibase.change-log=db/changelog/db.changelog-master.xml